{% set version = "1.0.9" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-iterators
  version: {{ version|replace("-", "_") }}

source:
  fn: iterators_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/iterators_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/iterators/iterators_{{ version }}.tar.gz
  sha256: de001e063805fdd124953b571ccb0ed2838c55e40cca2e9d283d8a90b0645e9b

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('iterators')"  # [not win]
    - "\"%R%\" -e \"library('iterators')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=iterators
  license: Apache 2.0
  summary: Support for iterators, which allow a programmer to traverse through all the elements
    of a vector, list, or other collection of data.
  license_family: APACHE

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
