appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: DzDqh8emPFGmwU1zZVyDUGM9Q+8YG0al+wEOTKqL/svv1pYcotVywFD5sNYcZrGKntUSJDN4W050PFuj/m6xyqix3pNg7wGot0NNKA+TWD/jM0e5tVHbeKed3kO8S7/kziKXOIleKdCBxwzxwNJRAt9Inr0AIxuKiXhhx0QcMWkQM1mDzAb7KpzEmtUgxiYhqqQn2y5VgZOoPJZ7vBF1ymGQ823TGXAxt+TemB7BEilApUr2aj25/JTvtnyNZzfzlCy0W2SivagkAB2QivaYWoDmr2PIougtPCI9nH9yH+QBcfXIa4xVCzYYGoXxpyCfzeklV/YiYodF7VEkPKucGHmDwR4rId81ip3+gjUdzfpNrME/nV3aL8+WyGMe8oy2OlIX1rgwHgwPPoLfv0srCejKXaGk4GdzBMXQLbSLcgUtNsLIzeCbnz34mTZcVgqO2LQjAmIIjyZQLAkLwgEgmpHteoND/rQMM5SQP/tDapyxvo8dXz4HwOX1JMjlQAAeEUsx7oW89jXuQSEpXiBhJgr7PQY+vgUz3MPXJkaF/jwR/Fm2opHOIRZCfjtEeIea8A3yEHbuMQwzyy/BAAhMfZjblJcKUlYYMC0CSHqhWu7uRs7KLoMV6YTFPJ8TScf7E951ttxQc3axBNtDuCQWmdOigtMxSNP9EpqzGWGESN0=}
bot:
  automerge: true
